name: Portfolio Deployment

on:
  push:
    branches:
    - master

jobs:
  build-and-deploy:
    runs-on: ubantu-latest
    steps:
    - name: Checkout
      uses: sctions/checkout@v1


    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRETS_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy static site to S3bucket
      run: aws s3 sync . s3://harsh-portfolio-devops --delete

      
